name: Deploy via Pterodactyl API
on:
  pull_request:
    branches:
      - stage
    
permissions:
  contents: read
  packages: read

jobs:
  build-deploy-restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: ./gradlew shadowJar --no-daemon
        env:
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload JAR via signed URL
      # https://github.com/pterodactyl/panel/issues/5393#issuecomment-3446548283
        run: |
          set -euo pipefail

          signed_url=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.PTERO_TOKEN }}" \
            -H "Accept: Application/vnd.pterodactyl.v1+json" \
            "${{ secrets.PTERO_PANEL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/files/upload?directory=%2Fplugins%2F" \
            | jq -r '.attributes.url')
          
          curl -X POST "$signed_url&directory=%2Fplugins%2F" \
            -F "files=@build/libs/TheatriaTime.jar" \
            -F "directory=/plugins/"

      - name: Restart server
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.PTERO_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"signal":"restart"}' \
            "${{ secrets.PTERO_PANEL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/power"